openapi: 3.0.0
info:
  title: Yelp Camp API
  version: 1.0.0
  description: API for managing campgrounds

paths:
  /campgrounds:
    get:
      summary: Get all campgrounds
      responses:
        '200':
          description: A list of campgrounds
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Campground'
    post:
      summary: Create a new campground
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Campground'
      responses:
        '201':
          description: Campground created

  /campgrounds/{id}:
    get:
      summary: Get a campground by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A single campground
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Campground'
    put:
      summary: Update a campground
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Campground'
      responses:
        '200':
          description: Campground updated
    delete:
      summary: Delete a campground
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Campground deleted

components:
  schemas:
    Campground:
      type: object
      properties:
        title:
          type: string
        # price:
        #   type: string
        # description:
        #   type: string
        location:
          type: string